spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb

    username: bestuser
    password: bestuser

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true